# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  fdforthehordeapi:
    build:
      context: "/Users/filipdadgar/RiderProjects/FDForthehordeAPI"
      dockerfile: "FDForthehordeAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/FDForthehordeAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "fdforthehordeapi:dev"
    ports: []
    volumes:
    - "/Users/filipdadgar/RiderProjects/FDForthehordeAPI/FDForthehordeAPI:/app:rw"
    - "/Users/filipdadgar/RiderProjects/FDForthehordeAPI:/src:rw"
    - "/Users/filipdadgar/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
