name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the API Docker image
      run: docker build . --file FDForthehordeAPI/Dockerfile --tag fdforthehordeapi:$(date +%s)

    - name: Build the Web Docker image
      run: docker build . --file FDForthehordeWeb/Dockerfile --tag fdforthehordeweb:$(date +%s)
